In [91]:
#Name : Ram Darekar
#Roll No : 114
#Batch : T2
#Assignment Title : Assignment 1


In [92]:
import numpy as np
import pandas as pd

In [93]:
a = np.zeros(5)
print(a,a.dtype)
a=a.astype(np.int32)
print(a,a.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [94]:
ones_array = np.ones(5,dtype="int")
ones_array

array([1, 1, 1, 1, 1])

In [95]:
b=np.array([[1,2,3],[2,3,3],[3,4,4]])
b.shape

(3, 3)

In [96]:
c=np.array([[1,2,3],[2,3,3],[3,4,4],[1,2,3]])
print(c)
print(c.shape,c.dtype)

[[1 2 3]
 [2 3 3]
 [3 4 4]
 [1 2 3]]
(4, 3) int64


In [97]:

a=np.swapaxes(c,0,1)


In [98]:
b=np.array([[1,2,3],[2,3,3],[3,4,4]])
print(np.swapaxes(b,0,1),"\n")

print(b.max(),"\n")
print(b.reshape(3,3),"\n")
print(np.linspace(0, 1, 5),"\n")

print(np.sort(b, axis=1))

[[1 2 3]
 [2 3 4]
 [3 3 4]] 

4 

[[1 2 3]
 [2 3 3]
 [3 4 4]] 

[0.   0.25 0.5  0.75 1.  ] 

[[1 2 3]
 [2 3 3]
 [3 4 4]]


In [99]:
print(np.sort(b, axis=None),"\n")

[1 2 2 3 3 3 3 4 4] 



In [100]:
# for reshape
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = arr2.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
# for arange and reshape
arr1=np.arange(2,11)
print(arr1) 
arr1=arr1.reshape(3,3)
print(arr1)
h=np.arange(2,21,2)
h

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [109]:
# arithmatic operations
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
print("--------------")
c=a/b
print(c)
print("--------------")
d=a*b
print(d) 
print("--------------")
e=a+b
print(e)
print("--------------")
f=a-b
print(f) 
print("--------------")
g=a**2  
print(g)
print("--------------")
h=a%2   
   



[[1 2 3]
 [6 7 8]]
[[ 7  8  9]
 [10 11 12]]
--------------
[[0.14285714 0.25       0.33333333]
 [0.6        0.63636364 0.66666667]]
--------------
[[ 7 16 27]
 [60 77 96]]
--------------
[[ 8 10 12]
 [16 18 20]]
--------------
[[-6 -6 -6]
 [-4 -4 -4]]
--------------
[[ 1  4  9]
 [36 49 64]]
--------------


In [103]:
# for array indexing and slicing
z=[1,2,56,54,'ram','shyam',23,2]
print(z)
print(z[1])

print(z[-4])

print(z[1:5])

[1, 2, 56, 54, 'ram', 'shyam', 23, 2]
2
ram
[2, 56, 54, 'ram']


In [108]:
#docstring 
?arr2
?arr1

Type:        ndarray
String form:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Length:      3
File:        c:\foundation of data science\venv\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : da

In [105]:
#Array attributes
print(arr2.ndim)  
print(a.ndim)
print(a.shape)
print(a.size)

2
2
(2, 3)
6


In [106]:
# self learning topics
# argmax and argmin
print(b.argmax())
print(b.argmin())
print(b.max()) 
print(b.min()) 


# difference
print(np.diff(b))

# linespace
print(np.linspace(0, 1, 5))

5
0
12
7
[[1 1]
 [1 1]]
[0.   0.25 0.5  0.75 1.  ]
