In [93]:
import numpy as np
import pandas as pd

In [94]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a = np.zeros(5)
print(a,a.dtype)
a=a.astype(np.int32)
print(a,a.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [97]:
ones_array = np.ones(5,dtype="int")
ones_array

array([1, 1, 1, 1, 1])

In [98]:
b=np.array([[1,2,3],[2,3,3],[3,4,4]])
b.shape

(3, 3)

In [99]:
c=np.array([[1,2,3],[2,3,3],[3,4,4],[1,2,3]])
print(c)
print(c.shape,c.dtype)

[[1 2 3]
 [2 3 3]
 [3 4 4]
 [1 2 3]]
(4, 3) int64


In [100]:

a=np.swapaxes(c,0,1)


In [92]:
b=np.array([[1,2,3],[2,3,3],[3,4,4]])
print(np.swapaxes(b,0,1),"\n")

print(b.max(),"\n")
print(b.reshape(3,3),"\n")
print(np.linspace(0, 1, 5),"\n")

print(np.sort(b, axis=1))

[[1 2 3]
 [2 3 4]
 [3 3 4]] 

4 

[[1 2 3]
 [2 3 3]
 [3 4 4]] 

[0.   0.25 0.5  0.75 1.  ] 

[[1 2 3]
 [2 3 3]
 [3 4 4]]
