In [2]:
#Name : Ram Darekar
#Roll No : 114
#Batch : T2
#Div : B


In [3]:
import numpy as np   #import numpy

In [4]:
a = np.zeros(5)  #create an array of zeros of size 5
print(a,a.dtype)
a=a.astype(np.int32)
print(a,a.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [38]:
ones_array = np.ones(5,dtype="int")   #create an array of ones of size 5
ones_array

array([1, 1, 1, 1, 1])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])   #2-D array

In [6]:

arr.ndim   # dimension of array

2

In [7]:
arr.shape # shape of array

(2, 3)

In [8]:
arr.size # total number of elements in array

6

In [9]:
arr.dtype # data type of array elements

dtype('int64')

In [10]:
arr.itemsize # size of each element in bytes

8

In [11]:
arr1 = np.array([[10, 20, 30],
                [40, 50, 60]])   #2-D array

print("Array 1 : \n", arr1)

Array 1 : 
 [[10 20 30]
 [40 50 60]]


In [12]:
arr1[0, 0]  # accessing element at 1st row and 1st column


np.int64(10)

In [13]:
arr1[1, 2]  # accessing element at 2nd row and 3rd column

np.int64(60)

In [14]:
arr1[0, :]  # accessing all elements of 1st row

array([10, 20, 30])

In [15]:
arr[:, 1]  # accessing all elements of 2nd column

array([2, 5])

In [16]:
arr1[0:2, 1:3] # accessing elements from 1st to 2nd row and 2nd to 3rd column

array([[20, 30],
       [50, 60]])

In [17]:
np.arange(5) # 1-D array from 0 to 4

array([0, 1, 2, 3, 4])

In [18]:
np.arange(2, 10) # 1-D array from 2 to 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2, 21, 2)   #table of 2 from 2 to 20

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arr3 = np.arange(9) # 1-D array from 0 to 8
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr3.reshape(3, 3)  # reshaping with 3 rows and 3 columns

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
arr.reshape(3, -1) # reshaping 1-D array to 2-D array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:



arr4 = np.array([[1, 2, 3], [6, 7, 8]])       #2-D array
b = np.array([[7, 8, 9], [10, 11, 12]])       #2-D array

# Print the arrays
print("Array arr4:\n", arr4)
print("Array b:\n", b)




Array arr4:
 [[1 2 3]
 [6 7 8]]
Array b:
 [[ 7  8  9]
 [10 11 12]]


In [24]:
# Division
div = arr4 / b
print("Division of arrays:\n", div)




Division of arrays:
 [[0.14285714 0.25       0.33333333]
 [0.6        0.63636364 0.66666667]]


In [25]:
# Multiplication
mul = arr4 * b
print("Multiplication of arrays:\n", mul)



Multiplication of arrays:
 [[ 7 16 27]
 [60 77 96]]


In [26]:

# Addition
add = arr4 + b
print("Addition of arrays:\n", add)




Addition of arrays:
 [[ 8 10 12]
 [16 18 20]]


In [27]:
# Subtraction
sub = arr4 - b
print("Subtraction of arrays:\n", sub)


Subtraction of arrays:
 [[-6 -6 -6]
 [-4 -4 -4]]


In [28]:

# Square of arr4
square = arr4 ** 2
print("Square of arr4:\n", square)


Square of arr4:
 [[ 1  4  9]
 [36 49 64]]


In [29]:
#Square of arr b
print("Square of arr b:\n", b ** 2) 


Square of arr b:
 [[ 49  64  81]
 [100 121 144]]


In [30]:


# Modulus of arr4 with 2
mod = arr4 % 2
print("Modulus of arr4 (arr4 % 2):\n", mod)
print("--------------")


Modulus of arr4 (arr4 % 2):
 [[1 0 1]
 [0 1 0]]
--------------


In [31]:
arr5 = np.array([4, 10, 2, 8])
print("Max element index :",np.argmax(arr5)) # index of max element
np.max(arr5)  # maximum element in array

Max element index : 1


np.int64(10)

In [32]:
np.min(arr5)  # minimum element in array

np.int64(2)

In [33]:
np.argmin(arr5)  # index of minimum element 

np.int64(2)

In [34]:
arr6 = np.linspace(0, 1, 5) #  5 evenly spaced numbers between 0 and 1
print(arr6) 


[0.   0.25 0.5  0.75 1.  ]


In [35]:
arr7 = np.array([10, 25, 30, 50]) # 1-D array
np.diff(arr7) # difference between consecutive elements

array([15,  5, 20])

In [36]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000029453B58540>
File:            c:\foundation of data science\venv\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set

In [37]:
arr7?

Type:        ndarray
String form: [10 25 30 50]
Length:      4
File:        c:\foundation of data science\venv\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    A